### ISSUE TITLE
"Field '___recordID' is not marked queryable"

### ISSUE THREAD

**Issue by stevenjamescox** [DevMountain/Timeline#11]
Andrew's suggested usage of "NSLog" gave me improved error information. The message I got when attempting a records fetch was "Field '___recordID' is not marked queryable". Tinkering around in my CloudKit dashboard fixed this.
==There may need to be something in the directions about making recordIDs queryable.

**Comment by armadsen** [comment]
Thanks, @stevenjamescox. We should fix this. Feel free to submit a pull request adding a note to the README, if you're so inclined. Otherwise, I'll fix it soon.
