### ISSUE TITLE
Adopting SyncableObject

### ISSUE THREAD

**Issue by niclaughter** [DevMountain/Timeline#4]
The instructions for Post and Comment on step 1 should clarify that those objects need to remove the `NSManagedObject` adoption and adopt `SyncableObject` after creation

**Comment by calebhicks** [comment]
@niclaughter Can you be more specific? Which line are you talking about?

> 1. Add a new `SyncableObject` Core Data entity to your managed object model. Add a `timestamp` Date attribute, a `recordName` String attribute, and a `recordIDData` NSData attribute. Set the `recordName` and `timestamp` attributes as required.

That one?

**Comment by niclaughter** [comment]
So when the objects are actually created, only sometimes do they automatically inherit from the parent class, we figured out. It wasn't doing so for a few of us, but some of us it was. Must just be an issue in Xcode, but I assumed it needed to be done manually since it didn't do it automatically for me and a couple others.
