### ISSUE TITLE
NSFetchedResultsController step confusing

### ISSUE THREAD

**Issue by niclaughter** [DevMountain/Timeline#5]
On the Timeline Scene - Post List Table View Controller step 4, it is confusing what it expects and seems to be in the wrong place.

**Comment by calebhicks** [comment]
@niclaughter Is that because you are used to this being done in the Model Controller and this step directs the student to do it on the view controller itself?

**Comment by niclaughter** [comment]
Oh disregard this, we were confusing fetching from the container and fetching for the views.
