### ISSUE TITLE
Timeline directions issue

### ISSUE THREAD

**Issue by SeanGilhuly** [DevMountain/Timeline#6]
@calebhicks 
Part 2:

Image Picker Controller

Add Post Scene

*Per the instructions, it would be helpful if it were more specific as to what view controller we are working on, when adding functions.  This specific instruction makes it seem like it is dealing with the AddPostDetailViewController when it is really the PhotoSelectViewController.  Thanks!

**Comment by calebhicks** [comment]
@SeanGilhuly If I were to rename that step to "Photo Select Child Scene" would that solve the issue?

**Comment by SeanGilhuly** [comment]
Perfect!

**Comment by calebhicks** [comment]
👍  Thanks @SeanGilhuly! Change pushed.
